<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: DejaVu Sans, sans-serif; color: #1f2937; font-size: 12px; }
    .header { border-bottom: 3px solid #0d5c8c; padding-bottom: 12px; margin-bottom: 20px; }
    .brand { font-size: 20px; font-weight: bold; color: #0d5c8c; }
    .subtitle { color: #6b7280; font-size: 11px; }
    .code-box { border: 2px dashed #0d5c8c; padding: 14px; text-align: center; margin: 18px 0; }
    .code-box .label { color: #6b7280; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; }
    .code-box .code { font-size: 26px; font-weight: bold; letter-spacing: 2px; color: #0d5c8c; font-family: DejaVu Sans Mono, monospace; }
    table.meta { width: 100%; margin-bottom: 16px; }
    table.meta td { padding: 4px 0; vertical-align: top; }
    table.meta td.label { color: #6b7280; width: 140px; }
    .section-title { font-weight: bold; margin-top: 18px; margin-bottom: 6px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    .medicines { white-space: pre-line; line-height: 1.6; }
    .footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 9px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; }
    .badge-active { background: #dbeafe; color: #1d4ed8; }
    .badge-dispensed { background: #f3f4f6; color: #4b5563; }
</style>
</head>
<body>

    <div class="header">
        <div class="brand">SwasthoLink</div>
        <div class="subtitle">Digitally signed e-prescription — verify by lookup code at any participating pharmacy</div>
    </div>

    <table class="meta">
        <tr>
            <td class="label">Patient</td>
            <td>{{ $prescription->patient_name }}</td>
            <td class="label">Issued</td>
            <td>{{ $prescription->created_at->format('d M Y, h:i A') }}</td>
        </tr>
        <tr>
            <td class="label">Prescribed by</td>
            <td>{{ $prescription->doctor->name }}</td>
            <td class="label">Expires</td>
            <td>{{ $prescription->expires_at?->format('d M Y') }}</td>
        </tr>
        @if ($prescription->doctor->doctorProfile)
        <tr>
            <td class="label">BMDC No.</td>
            <td>{{ $prescription->doctor->doctorProfile->bmdc_number }}</td>
            <td class="label">Status</td>
            <td>
                <span class="badge {{ $prescription->status === 'active' ? 'badge-active' : 'badge-dispensed' }}">
                    {{ ucfirst($prescription->status) }}
                </span>
            </td>
        </tr>
        @endif
        @if ($prescription->hospital)
        <tr>
            <td class="label">Hospital</td>
            <td colspan="3">{{ $prescription->hospital->name }}</td>
        </tr>
        @endif
    </table>

    <div class="code-box">
        <div class="label">Pharmacy Lookup Code</div>
        <div class="code">{{ $prescription->lookup_code }}</div>
    </div>

    <div class="section-title">Medicines</div>
    <div class="medicines">{{ $prescription->medicines }}</div>

    @if ($prescription->notes)
    <div class="section-title">Notes</div>
    <div class="medicines">{{ $prescription->notes }}</div>
    @endif

    <div class="footer">
        Generated by SwasthoLink on {{ now()->format('d M Y, h:i A') }}. This prescription is cryptographically signed
        (RSA-2048 / SHA-256) with the issuing doctor's private key; any pharmacist can verify its authenticity by
        entering the lookup code above at swastholink.test/pharmacist/lookup. A signature mismatch means the record
        has been altered since it was signed.
    </div>

</body>
</html>
